### ISSUE TITLE
Improve file structure and README.md

### ISSUE THREAD

**Issue by MaanasVohra** [SSPrafulTondomker/ShareNotes#3]
Need to provide a file structure with: 
<ul>
<li>The styling files need to be in assets/css</li>
<li>The external js libraries need to be in assets/js/lib</li>
<li>The js files need to be in assets/js</li>
<li>Proper nomenclature of files</li>
</ul>

Also the README.md has to be updated for upcoming contributors.

**Comment by SSPrafulTondomker** [comment]
Done
